name: Ubuntu Make

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt-get 
      run: sudo apt-get install libncurses-dev
    - name: make
      run: make
